name: Release

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [release]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JavaScript
        uses: richardsolomou/ras-stack/actions/setup-js@v0.8.3

      # TODO: Uncomment this for your own repository
      # - name: Run Changesets (version or publish)
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     version: pnpm run changeset:version
      #     publish: pnpm run changeset:publish
      #     commit: "ci: version packages"
      #     title: "ci: version packages"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Auto-merge Changesets PR
      #   if: steps.changesets.outputs.hasChangesets == 'true'
      #   run: |
      #     gh pr merge --squash "$PR_NUMBER"
      #     gh api --method POST /repos/$REPO/dispatches -f 'event_type=release'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REPO: ${{ github.repository }}
      #     PR_NUMBER: ${{ steps.changesets.outputs.pullRequestNumber }}
